services:
  op-connect-api:
    container_name: "op-connect-api"
    image: 1password/connect-api:1.6
    restart: always
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"
  op-connect-sync:
    container_name: "op-connect-sync"
    image: 1password/connect-sync:1.6
    restart: always
    volumes:
      - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "data:/home/opuser/.op/data"

volumes:
  data:
