services:
  wg-easy:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: wg-easy
    env_file:
      - .env
    image: weejewel/wg-easy:latest
    ports:
      - "51820:51820/udp"
    restart: always
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - "./wg-easy:/etc/wireguard"
