---
- hosts: all
  vars:
    base_dir: "Developing"
    project_name: "portainer"
    service_dir: "{{ base_dir }}/{{ project_name }}"
  vars_prompt:
    - name: "docker_network"
      prompt: "Enter the name of the docker network to use"
      default: "nginx-proxy-manager"

  tasks:
    - name: Create service directory
      file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Add networks block if docker_network is set
      when: docker_network is defined
      blockinfile:
        path: "{{ service_dir }}/docker-compose.yml"
        block: |
          networks:
            default:
              external: true
              name: "{{ docker_network }}"

    - name: Start services
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
