---
- hosts: all
  vars:
    base_dir: "Developing"
    project_name: "1password-connect"
    service_dir: "{{ base_dir }}/{{ project_name }}"
    docker_api_service_name: "op-connect-api"
    onepassword_key_item: "Cloudflare API Token"
  vars_prompt:
    - name: op_token_name
      prompt: What should be the token name in 1Password
      default: "wanli"
      private: false
    - name: domain
      prompt: Which domain would you like to use
      default: "op-connect.tomy.me"
      private: false

  tasks:
    # Create service directory
    - name: Create service directory
      file:
        path: "{{ service_dir }}"
        state: directory

    # Create docker-compose.yml
    - name: Create docker-compose.yml
      copy:
        dest: "{{ service_dir }}/docker-compose.yml"
        content: |
          version: "3.4"
          services:
            {{ docker_api_service_name }}:
              image: 1password/connect-api:latest
              restart: always
              volumes:
                - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
                - "data:/home/opuser/.op/data"
            op-connect-sync:
              image: 1password/connect-sync:latest
              restart: always
              volumes:
                - "./1password-credentials.json:/home/opuser/.op/1password-credentials.json"
                - "data:/home/opuser/.op/data"

          networks:
            default:
              external: true
              name: "nginx-proxy-manager"

          volumes:
            data:

    # Create credentials
    - name: Create credentials
      delegate_to: localhost
      shell: "op connect server create {{ op_token_name }}"

    # Upload credentials
    - name: Upload credentials to server
      copy:
        src: 1password-credentials.json
        dest: "{{ service_dir }}/1password-credentials.json"
        mode: "0400"

    # Remove local credentials
    - name: Discard local credentials
      local_action: file path=1password-credentials.json state=absent

    # Start the service
    - name: Start services
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach

    # Add DNS record to Cloudflare
    - name: Add DNS record to Cloudflare
      community.general.cloudflare_dns:
        api_token: "{{ lookup('community.general.onepassword', '{{ onepassword_key_item }}', field='credential') }}"
        proxied: true
        record: "{{ domain.split('.')[0] }}"
        type: A
        value: "{{ ansible_host }}"
        zone: "{{ domain.split('.')[-2:] | join('.') }}"

    # TODO: Add service to NPM
