# https://github.com/louislam/uptime-kuma#-how-to-install
---
- hosts: all
  vars:
    base_dir: "Developing"
    project_name: "uptime-kuma"
    service_dir: "{{ base_dir }}/{{ project_name }}"
  vars_prompt:
    - name: docker_network
      prompt: Which network should Uptime Kuma be connected to
      default: "caddy"
      private: false
    - name: domain
      prompt: Which domain would you like to use
      default: "kuma.tomy.me"
      private: false

  tasks:
    - name: Create uptime-kuma directory
      file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create docker-compose.yml
      copy:
        dest: "{{ service_dir }}/docker-compose.yml"
        content: |
          services:
            uptime-kuma:
              image: louislam/uptime-kuma:1
              restart: always
              volumes:
                - data:/app/data

          networks:
            default:
              external: true
              name: "{{ docker_network }}"

          volumes:
            data:

    - name: Start services
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach

    - name: Setup DNS record
      import_tasks: ../utils/cloudflare_dns.yml

    # TODO: Add entry to Caddyfile
