# https://plausible.io/docs/self-hosting
---
- name: Playbook for deploying Plausible Analytics
  hosts: all
  vars:
    base_dir: Developing
    project_name: plausible-analytics
    service_dir: "{{ base_dir }}/{{ project_name }}"
  vars_prompt:
    - name: docker_network
      prompt: Enter the name of the docker network to use
      private: false
    - name: domain
      prompt: Which domain would you like to use
      private: false

  tasks:
    - name: Check if plausible-analytics directory is cloned
      ansible.builtin.stat:
        path: "{{ service_dir }}"
      register: git_dir

    - name: Stash git changes if cloned # noqa: command-instead-of-module
      when: git_dir.stat.exists
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: git stash
      changed_when: false # git stash does not return a changed status, but it might stash changes

    - name: Clone the repository
      ansible.builtin.git:
        repo: https://github.com/plausible/hosting
        dest: "{{ service_dir }}"
        force: true
        version: bb6decee4d33ccf84eb235b6053443a01498db53
        refspec: bb6decee4d33ccf84eb235b6053443a01498db53

    - name: Unstash git changes if cloned # noqa: command-instead-of-module
      when: git_dir.stat.exists
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: git stash pop
      register: unstash_output
      failed_when:
        - unstash_output.failed
        - not 'No stash entries found' in unstash_output.stderr
      changed_when: not unstash_output.failed

    - name: Remove port exposing
      ansible.builtin.replace:
        path: "{{ service_dir }}/docker-compose.yml"
        regexp: ^\s+ports:\n\s+\-\s+"?8000:8000"?\n
        replace: ""

    - name: Check BASE_URL is set
      ansible.builtin.lineinfile:
        path: "{{ service_dir }}/plausible-conf.env"
        state: absent
        search_string: BASE_URL=replace-me
      check_mode: true
      register: base_url_set

    - name: Setup BASE_URL
      when: base_url_set.found
      ansible.builtin.lineinfile:
        path: "{{ service_dir }}/plausible-conf.env"
        state: present
        regexp: ^BASE_URL=replace-me
        line: BASE_URL=http://{{ domain }}

    - name: Check SECRET_KEY_BASE is set
      ansible.builtin.lineinfile:
        path: "{{ service_dir }}/plausible-conf.env"
        state: absent
        search_string: SECRET_KEY_BASE=replace-me
      check_mode: true
      register: secret_key_base_set

    - name: Generate SECRET_KEY_BASE
      when: secret_key_base_set.found
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          openssl rand -base64 64 | tr -d '\n'
      register: secret_key_base
      changed_when: false

    - name: Setup SECRET_KEY_BASE
      when: secret_key_base_set.found
      ansible.builtin.lineinfile:
        path: "{{ service_dir }}/plausible-conf.env"
        state: present
        regexp: ^SECRET_KEY_BASE=replace-me
        line: SECRET_KEY_BASE={{ secret_key_base.stdout }}

    - name: Add networks block if docker_network is set
      when: docker_network is defined
      ansible.builtin.blockinfile:
        path: "{{ service_dir }}/docker-compose.yml"
        block: |
          networks:
            default:
              external: true
              name: "{{ docker_network }}"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull
      changed_when: false

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
      changed_when: false

    - name: Setup DNS record
      ansible.builtin.import_tasks: ../../utils/cloudflare-dns-cname.yml

    # TODO: Setup reverse proxy

    # TODO: Custom configuration
    # https://plausible.io/docs/self-hosting-configuration
