# https://github.com/louislam/uptime-kuma#-how-to-install
---
- name: Playbook for deploying Uptime Kuma
  hosts: all
  vars:
    base_dir: Developing
    project_name: uptime-kuma
    service_dir: "{{ base_dir }}/{{ project_name }}"
  vars_prompt:
    - name: docker_network
      prompt: Which network should Uptime Kuma be connected to
      default: caddy
      private: false
    - name: domain
      prompt: Which domain would you like to use
      default: kuma.tomy.me
      private: false

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Add networks block if docker_network is set
      when: docker_network is defined
      ansible.builtin.blockinfile:
        path: "{{ service_dir }}/docker-compose.yml"
        block: |
          networks:
            default:
              external: true
              name: "{{ docker_network }}"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull
      changed_when: false

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
      changed_when: false

    - name: Setup DNS record
      ansible.builtin.import_tasks: ../../utils/cloudflare-dns-cname.yml

    # TODO: Add entry to Caddyfile
