---
# https://askubuntu.com/a/1170073/1226685
# https://stackoverflow.com/a/52016887/10325430
#
# Remember to add become: true when importing this task
#
- name: Stop systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: stopped
  register: systemd_resolved_stopped

- name: Disable systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: false

- name: Mask systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    masked: true

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: systemd_resolved_stopped.changed

- name: Check /etc/resolv.conf
  ansible.builtin.copy:
    src: ./resolv.conf
    dest: /etc/resolv.conf
    mode: "preserve"
  check_mode: true
  register: resolv_conf_check

- name: Backup /etc/resolv.conf if needed
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.bak
    remote_src: true
    force: true
    mode: "preserve"
  when: systemd_resolved_stopped.changed and resolv_conf_check.changed

- name: Update /etc/resolv.conf
  ansible.builtin.copy:
    src: ./resolv.conf
    dest: /etc/resolv.conf
    force: true
    mode: "0644"
  when: systemd_resolved_stopped.changed and resolv_conf_check.changed

- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Restart Docker if installed
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
  when: systemd_resolved_stopped.changed and not docker_installed.failed
