---
- hosts: all
  vars:
    base_dir: "Developing"
    project_name: "k-backend"
    service_dir: "{{ base_dir }}/{{ project_name }}"
  vars_prompt:
    - name: "docker_network"
      prompt: "Enter the name of the docker network to use"
      default: "nginx-proxy-manager"
    - name: domain
      prompt: What domain would you like to use
      default: "k.tomy.me"
      private: false

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Add networks block if docker_network is set
      when: docker_network is defined
      ansible.builtin.blockinfile:
        path: "{{ service_dir }}/docker-compose.yml"
        block: |
          networks:
            default:
              external: true
              name: "{{ docker_network }}"

    - name: Create instance directory
      ansible.builtin.file:
        path: "{{ service_dir }}/instance"
        state: directory

    # TODO: Create production.env

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach

    - name: Setup DNS record
      ansible.builtin.import_tasks: ../../utils/cloudflare-dns-cname.yml

    # TODO: Configure Nginx Proxy Manager
