# https://hub.docker.com/_/caddy
---
- hosts: all
  vars:
    base_dir: "Developing"
    project_name: "caddy"
    service_dir: "{{ base_dir }}/{{ project_name }}"

  tasks:
    - name: Create service directory
      file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create 'caddy' network
      community.docker.docker_network:
        name: caddy

    - name: Check if Caddyfile exists
      stat:
        path: "{{ service_dir }}/Caddyfile"
      register: caddyfile

    - name: Create Caddyfile if not exists
      when: not caddyfile.stat.exists
      copy:
        dest: "{{ service_dir }}/Caddyfile"
        content: ":80 {\n    root * /usr/share/caddy\n    file_server\n}"

    - name: Create docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Start services
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
