# https://hub.docker.com/_/caddy
---
- hosts: all
  vars:
    base_dir: Developing
    project_name: caddy
    service_dir: "{{ base_dir }}/{{ project_name }}"

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create 'caddy' network
      community.docker.docker_network:
        name: caddy

    - name: Check if Caddyfile exists
      ansible.builtin.stat:
        path: "{{ service_dir }}/Caddyfile"
      register: caddyfile

    - name: Create Caddyfile if not exists
      when: not caddyfile.stat.exists
      ansible.builtin.copy:
        dest: "{{ service_dir }}/Caddyfile"
        content: ":80 {\n    root * /usr/share/caddy\n    file_server\n}"

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
