# https://github.com/thedevs-network/kutt#docker
---
- hosts: all
  vars:
    base_dir: Developing
    project_name: kutt
    service_dir: "{{ base_dir }}/{{ project_name }}"
    db_password: "{{ lookup('password', '/tmp/passwordfile') }}"
    jwt_secret: "{{ lookup('password', '/tmp/passwordfile') }}"
  vars_prompt:
    - name: docker_network
      prompt: Enter the name of the docker network to use
      default: caddy
    - name: domain
      prompt: Which domain would you like to use
      default: kutt.tomy.me
      private: false

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory

    - name: Check .env file
      ansible.builtin.stat:
        path: "{{ service_dir }}/.env"
      register: dot_env

    - name: Create .env file
      ansible.builtin.copy:
        src: .env
        dest: "{{ service_dir }}/.env"
      when: not dot_env.stat.exists

    - name: Setup DEFAULT_DOMAIN in .env file
      ansible.builtin.lineinfile:
        path: .env
        regexp: ^DEFAULT_DOMAIN=$
        line: DEFAULT_DOMAIN={{ domain }}
        backrefs: true
      when: not dot_env.stat.exists

    - name: Setup POSTGRES_PASSWORD in .env file
      ansible.builtin.lineinfile:
        path: .env
        regexp: ^POSTGRES_PASSWORD=$
        line: POSTGRES_PASSWORD={{ db_password }}
        backrefs: true
      when: not dot_env.stat.exists

    - name: Setup DB_PASSWORD in .env file
      ansible.builtin.lineinfile:
        path: .env
        regexp: ^DB_PASSWORD=$
        line: DB_PASSWORD={{ db_password }}
        backrefs: true
      when: not dot_env.stat.exists

    - name: Setup JWT_SECRET in .env file
      ansible.builtin.lineinfile:
        path: .env
        regexp: ^JWT_SECRET=$
        line: JWT_SECRET={{ jwt_secret }}
        backrefs: true
      when: not dot_env.stat.exists

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Add networks block if docker_network is set
      when: docker_network is defined
      ansible.builtin.blockinfile:
        path: "{{ service_dir }}/docker-compose.yml"
        block: |
          networks:
            default:
              external: true
              name: "{{ docker_network }}"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull
      changed_when: false

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
      changed_when: false

    - name: Setup DNS record
      ansible.builtin.import_tasks: ../../utils/cloudflare-dns-cname.yml

    # TODO: Setup reverse proxy
