# https://github.com/umputun/remark42/blob/master/docker-compose.yml
services:
  remark42:
    container_name: "remark42"
    env_file:
      - remark42.env
    hostname: "remark42"
    image: umputun/remark42:v1.13.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    restart: "always"
    volumes:
      - data:/srv/var

volumes:
  data:
