services:
  agent:
    container_name: portainer_agent
    image: "portainer/agent:2.16.2"
    ports:
      - "9001:9001"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
