# https://docs.portainer.io/start/agent/docker/linux
---
- name: Playbook for deploying Portainer agent
  hosts: all
  vars:
    base_dir: Developing
    project_name: portainer-agent
    service_dir: "{{ base_dir }}/{{ project_name }}"

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory
        mode: "0755"

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"
        mode: "0755"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull
      changed_when: false

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
      changed_when: false

    - name: Show portainer host configuration guide
      ansible.builtin.debug:
        msg: "Environment address: {{ ansible_host }}:9001"
