---
- hosts: all
  tasks:
    - name: Install required packages
      become: true
      ansible.builtin.apt:
        name:
          - aptitude
          - python3-pip
        state: latest
        update_cache: true
