# https://github.com/NVIDIA/ansible-role-nvidia-driver
---
- name: Playbook for installing NVIDIA drivers and CUDA
  hosts: all
  become: true
  gather_facts: true
  roles:
    - nvidia.nvidia_driver
