---
- hosts: all
  become: true

  tasks:
    - name: Mask sleep.target
      systemd:
        name: sleep.target
        masked: true

    - name: Mask suspend.target
      systemd:
        name: suspend.target
        masked: true

    - name: Mask hibernate.target
      systemd:
        name: hibernate.target
        masked: true

    - name: Mask hybrid-sleep.target
      systemd:
        name: hybrid-sleep.target
        masked: true
