---
- name: Playbook for setting a system to never sleep
  hosts: all
  become: true
  tasks:
    - name: Mask sleep.target
      ansible.builtin.systemd_service:
        name: sleep.target
        masked: true

    - name: Mask suspend.target
      ansible.builtin.systemd_service:
        name: suspend.target
        masked: true

    - name: Mask hibernate.target
      ansible.builtin.systemd_service:
        name: hibernate.target
        masked: true

    - name: Mask hybrid-sleep.target
      ansible.builtin.systemd_service:
        name: hybrid-sleep.target
        masked: true
