# https://docs.docker.com/engine/install/ubuntu/
---
- hosts: all
  gather_facts: true
  tasks:
    # Set up the repository
    - name: Install required system packages
      become: true
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - gnupg
        state: present
        update_cache: true

    - name: Add Docker GPG apt Key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: "0644"
        force: true

    - name: Add Docker Repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    # Install Docker
    - name: Install Docker
      become: true
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: true

    # Add user to docker group
    - name: Adding user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true

    # Enable docker service restart on boot
    - name: Enable service docker and ensure it is not masked
      ansible.builtin.systemd:
        name: docker
        enabled: true
        masked: false

    - name: Enable service containerd and ensure it is not masked
      ansible.builtin.systemd:
        name: containerd
        enabled: true
        masked: false

    # Install docker module for Python
    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose

    # Relogin to gain access to docker
    - name: Reset SSH connection
      ansible.builtin.meta: reset_connection

    # Save docker version
    - name: Save docker version
      ansible.builtin.command: docker version --format '{{ '{{' }}.Server.Version{{ '}}' }}'
      register: docker_version
      changed_when: false

    # Save docker compose version
    - name: Save docker compose version
      ansible.builtin.command: docker compose version --short
      register: docker_compose_version
      changed_when: false

    # Output versions
    - name: Output versions
      ansible.builtin.debug:
        msg: "Docker version: {{ docker_version.stdout }}    Docker Compose version: {{ docker_compose_version.stdout }}"
