---
- hosts: all
  vars:
    username: tomy0000000
    public_key: "{{ lookup('community.general.onepassword', 'DigitalOcean Key', field='public key') }}"
  tasks:
    - name: Setup non-root user
      ansible.builtin.import_tasks: ../utils/non-root-user.yml
