---
- name: Playbook for setting up a non-root user on Linode servers
  hosts: all
  vars:
    username: tomy0000000
    public_key: "{{ lookup('community.general.onepassword', 'Linode Key', field='public key') }}"
  tasks:
    - name: Setup non-root user
      ansible.builtin.import_tasks: ../utils/non-root-user.yml
