---
- hosts: all
  vars:
    username: "tomy0000000"
    public_key: "https://github.com/tomy0000000.keys"
  tasks:
    - name: Setup non-root user
      ansible.builtin.import_tasks: ../utils/non-root-user.yml
