services:
  nginx-proxy-manager:
    container_name: "nginx-proxy-manager"
    image: "jc21/nginx-proxy-manager:2.9.22"
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    restart: "always"
    volumes:
      - "./data:/data"
      - "./letsencrypt:/etc/letsencrypt"

networks:
  default:
    external: true
    name: "nginx-proxy-manager"
