# https://nginxproxymanager.com/setup/
---
- name: Playbook for deploying nginx Proxy Manager
  hosts: all
  vars:
    service_dir: Developing/nginx-proxy-manager

  tasks:
    - name: Create service directory
      ansible.builtin.file:
        path: "{{ service_dir }}"
        state: directory
        mode: "0755"

    - name: Create 'nginx-proxy-manager' network
      community.docker.docker_network:
        name: nginx-proxy-manager

    - name: Create docker-compose.yml
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"
        mode: "0755"

    - name: Pull images
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull
      changed_when: false

    - name: Start services
      ansible.builtin.command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
      changed_when: false
