# https://nginxproxymanager.com/setup/
---
- hosts: all
  vars:
    service_dir: "Developing/nginx-proxy-manager"

  tasks:
    - name: Create service directory
      file:
        path: "{{ service_dir }}"
        state: directory

    - name: Create 'nginx-proxy-manager' network
      community.docker.docker_network:
        name: nginx-proxy-manager

    - name: Create docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: "{{ service_dir }}/docker-compose.yml"

    - name: Pull images
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose pull

    - name: Start services
      command:
        chdir: "{{ service_dir }}"
        cmd: docker compose up --detach
